/**
 * Jewellery Ledger - Seeded Demo Master Data
 * Business: Shree Ganesh Jewellers, New Road, Kathmandu
 */

window.DEFAULT_SEED_DATA = {
  business: {
    name: "Shree Ganesh Jewellers",
    nepaliName: "श्री गणेश ज्वेलर्स",
    tagline: "Jewellery Retail & Trading Excellence",
    address: "New Road, Ward 22, Kathmandu, Nepal",
    nepaliAddress: "न्युरोड, वडा नं. २२, काठमाडौं, नेपाल",
    phone: "01-4256789, 9851023456",
    email: "info@shreeganeshjewellers.demo",
    pan: "601245892",
    proprietor: "सबिन धमला (Subin Dhamala)",
    currency: "NPR",
    fiscalYear: "2083/084",
    defaultDueDays: 30,
    interestRateMonthly: 1.5
  },

  users: [
    {
      id: "USR-001",
      name: "Subin Dhamala (Admin)",
      email: "admin@demo.com",
      role: "Admin",
      avatar: "SD",
      permissions: ["view", "create", "edit", "delete", "approve", "print", "export", "manage_rates", "manage_users", "view_reports", "view_audit"]
    },
    {
      id: "USR-002",
      name: "Prakash Acharya",
      email: "manager@demo.com",
      role: "Manager",
      avatar: "PA",
      permissions: ["view", "create", "edit", "approve", "print", "export", "manage_rates", "view_reports", "view_audit"]
    },
    {
      id: "USR-003",
      name: "Sunil Shrestha",
      email: "accountant@demo.com",
      role: "Accountant",
      avatar: "SS",
      permissions: ["view", "create", "edit", "print", "export", "view_reports"]
    },
    {
      id: "USR-004",
      name: "Aarati Thapa",
      email: "cashier@demo.com",
      role: "Cashier",
      avatar: "AT",
      permissions: ["view", "create", "print"]
    },
    {
      id: "USR-005",
      name: "Auditor Demo",
      email: "viewer@demo.com",
      role: "Viewer",
      avatar: "VD",
      permissions: ["view", "print"]
    }
  ],

  metalRates: [
    {
      id: "RATE-001",
      metal: "Gold",
      purity: "24K",
      ratePerGram: 19200,
      ratePer10Gram: 192000,
      ratePerTola: 223949,
      unit: "Gram",
      effectiveDate: "2026-09-15",
      source: "Federation of Nepal Gold and Silver Dealers' Association (FENEGOSIDA)",
      fetchMethod: "Automatic",
      status: "Verified",
      verifiedBy: "Subin Dhamala",
      timestamp: "2026-09-15 09:30 AM"
    },
    {
      id: "RATE-002",
      metal: "Gold",
      purity: "22K",
      ratePerGram: 17600,
      ratePer10Gram: 176000,
      ratePerTola: 205286,
      unit: "Gram",
      effectiveDate: "2026-09-15",
      source: "FENEGOSIDA",
      fetchMethod: "Automatic",
      status: "Verified",
      verifiedBy: "Subin Dhamala",
      timestamp: "2026-09-15 09:30 AM"
    },
    {
      id: "RATE-003",
      metal: "Gold",
      purity: "18K",
      ratePerGram: 14400,
      ratePer10Gram: 144000,
      ratePerTola: 167962,
      unit: "Gram",
      effectiveDate: "2026-09-15",
      source: "FENEGOSIDA",
      fetchMethod: "Automatic",
      status: "Verified",
      verifiedBy: "Subin Dhamala",
      timestamp: "2026-09-15 09:30 AM"
    },
    {
      id: "RATE-004",
      metal: "Silver",
      purity: "Fine (99.9%)",
      ratePerGram: 250,
      ratePer10Gram: 2500,
      ratePerTola: 2916,
      unit: "Gram",
      effectiveDate: "2026-09-15",
      source: "FENEGOSIDA",
      fetchMethod: "Automatic",
      status: "Verified",
      verifiedBy: "Subin Dhamala",
      timestamp: "2026-09-15 09:30 AM"
    },
    {
      id: "RATE-005",
      metal: "Silver",
      purity: "92.5% Chandi",
      ratePerGram: 231,
      ratePer10Gram: 2310,
      ratePerTola: 2694,
      unit: "Gram",
      effectiveDate: "2026-09-15",
      source: "FENEGOSIDA",
      fetchMethod: "Manual",
      status: "Verified",
      verifiedBy: "Prakash Acharya",
      timestamp: "2026-09-15 09:35 AM"
    },
    // Historical Rates
    {
      id: "RATE-H01",
      metal: "Gold",
      purity: "24K",
      ratePerGram: 18500,
      ratePer10Gram: 185000,
      ratePerTola: 215784,
      unit: "Gram",
      effectiveDate: "2026-09-01",
      source: "FENEGOSIDA",
      fetchMethod: "Automatic",
      status: "Verified",
      verifiedBy: "Subin Dhamala",
      timestamp: "2026-09-01 10:00 AM"
    },
    {
      id: "RATE-H02",
      metal: "Gold",
      purity: "22K",
      ratePerGram: 16950,
      ratePer10Gram: 169500,
      ratePerTola: 197705,
      unit: "Gram",
      effectiveDate: "2026-09-01",
      source: "FENEGOSIDA",
      fetchMethod: "Automatic",
      status: "Verified",
      verifiedBy: "Subin Dhamala",
      timestamp: "2026-09-01 10:00 AM"
    },
    {
      id: "RATE-H03",
      metal: "Gold",
      purity: "24K",
      ratePerGram: 18200,
      ratePer10Gram: 182000,
      ratePerTola: 212285,
      unit: "Gram",
      effectiveDate: "2026-08-15",
      source: "FENEGOSIDA",
      fetchMethod: "Automatic",
      status: "Verified",
      verifiedBy: "Subin Dhamala",
      timestamp: "2026-08-15 10:00 AM"
    }
  ],

  businessSources: [
    {
      id: "SRC-0001",
      name: "Walk-in Customer",
      type: "Direct",
      description: "Direct retail customers visiting the New Road showroom",
      status: "Active",
      createdAt: "2026-01-01"
    },
    {
      id: "SRC-0002",
      name: "Facebook",
      type: "Marketing",
      description: "Social media inquiries and ad campaigns",
      status: "Active",
      createdAt: "2026-01-10"
    },
    {
      id: "SRC-0003",
      name: "Instagram",
      type: "Marketing",
      description: "Instagram bridal jewellery campaign inquiries",
      status: "Active",
      createdAt: "2026-02-01"
    },
    {
      id: "SRC-0004",
      name: "Referral - Hari",
      type: "Referral",
      description: "Clients recommended by jeweler partner Hari Shrestha",
      status: "Active",
      createdAt: "2026-02-15"
    },
    {
      id: "SRC-0005",
      name: "Referral - Ram",
      type: "Referral",
      description: "Clients referred by artisan Ram Kumar",
      status: "Active",
      createdAt: "2026-03-01"
    },
    {
      id: "SRC-0006",
      name: "Existing Customer",
      type: "Direct",
      description: "Repeat and loyal family customers",
      status: "Active",
      createdAt: "2026-01-01"
    },
    {
      id: "SRC-0007",
      name: "Dealer",
      type: "Dealer",
      description: "Wholesale bullion and retail reseller accounts",
      status: "Active",
      createdAt: "2026-01-15"
    },
    {
      id: "SRC-0008",
      name: "Corporate",
      type: "Corporate",
      description: "Institutional clients, awards, and wedding gifting",
      status: "Active",
      createdAt: "2026-04-01"
    },
    {
      id: "SRC-0009",
      name: "Branch Kathmandu",
      type: "Branch",
      description: "Referrals from Boudha and Patan counters",
      status: "Active",
      createdAt: "2026-03-10"
    },
    {
      id: "SRC-0010",
      name: "Other",
      type: "Other",
      description: "General ad-hoc sources",
      status: "Active",
      createdAt: "2026-01-01"
    }
  ],

  customers: [
    {
      id: "CUS-0001",
      name: "Ram Sharma",
      localName: "राम शर्मा",
      mobile: "9841234567",
      altPhone: "01-4912345",
      email: "ram.sharma@nepal.test",
      address: "Jorpati, Gokarneshwor-5",
      localAddress: "गोकर्णेश्वर न.पा. ५, जोरपाटी, काठमाडौं",
      province: "Bagmati",
      district: "Kathmandu",
      municipality: "Gokarneshwor",
      ward: "5",
      customerType: "Retail Customer",
      sourceId: "SRC-0001",
      pan: "602341981",
      openingBalance: 0,
      creditLimit: 500000,
      notes: "Frequent gold bridal buyer. Collateral khata maintained.",
      status: "Active",
      createdAt: "2026-05-15"
    },
    {
      id: "CUS-0002",
      name: "Sita Shrestha",
      localName: "सीता श्रेष्ठ",
      mobile: "9851098765",
      altPhone: "01-5534120",
      email: "sita.shrestha@nepal.test",
      address: "Mangalbazar, Patan-12",
      localAddress: "पाटन-१२, मंगलबजार, ललितपुर",
      province: "Bagmati",
      district: "Lalitpur",
      municipality: "Lalitpur",
      ward: "12",
      customerType: "Regular Customer",
      sourceId: "SRC-0004",
      pan: "",
      openingBalance: 0,
      creditLimit: 300000,
      notes: "Referred by Hari Shrestha. Always pays promptly.",
      status: "Active",
      createdAt: "2026-06-01"
    },
    {
      id: "CUS-0003",
      name: "Hari Prasad Acharya",
      localName: "हरि प्रसाद आचार्य",
      mobile: "9813245678",
      altPhone: "01-6612987",
      email: "hari.ach@nepal.test",
      address: "Suryabinayak-2, Bhaktapur",
      localAddress: "सूर्यविनायक न.पा. २, कटुञ्जे, भक्तपुर",
      province: "Bagmati",
      district: "Bhaktapur",
      municipality: "Suryabinayak",
      ward: "2",
      customerType: "Wholesale Customer",
      sourceId: "SRC-0007",
      pan: "603819201",
      openingBalance: 0,
      creditLimit: 1500000,
      notes: "Buys 24K and 22K chains in volume.",
      status: "Active",
      createdAt: "2026-04-10"
    },
    {
      id: "CUS-0004",
      name: "Mina Gurung",
      localName: "मिना गुरुङ",
      mobile: "9803112233",
      altPhone: "",
      email: "mina.gurung@nepal.test",
      address: "Chabahil-7, Kathmandu",
      localAddress: "काठमाडौं म.न.पा. ७, चाबहिल",
      province: "Bagmati",
      district: "Kathmandu",
      municipality: "Kathmandu",
      ward: "7",
      customerType: "Retail Customer",
      sourceId: "SRC-0002",
      pan: "",
      openingBalance: 0,
      creditLimit: 200000,
      notes: "Found us via Facebook bridal advertisement.",
      status: "Active",
      createdAt: "2026-07-05"
    },
    {
      id: "CUS-0005",
      name: "Bikash Thapa",
      localName: "बिकेश थापा",
      mobile: "9849556677",
      altPhone: "",
      email: "bikash.thapa@nepal.test",
      address: "New Baneshwor-10, Kathmandu",
      localAddress: "काठमाडौं म.न.पा. १०, नयाँ बानेश्वर",
      province: "Bagmati",
      district: "Kathmandu",
      municipality: "Kathmandu",
      ward: "10",
      customerType: "Retail Customer",
      sourceId: "SRC-0003",
      pan: "",
      openingBalance: 0,
      creditLimit: 250000,
      notes: "Instagram customer for engagement diamond rings.",
      status: "Active",
      createdAt: "2026-08-01"
    },
    {
      id: "CUS-0006",
      name: "Anita Karki",
      localName: "अनिता कार्की",
      mobile: "9860123456",
      altPhone: "01-4412349",
      email: "anita.karki@nepal.test",
      address: "Maharajgunj-3, Kathmandu",
      localAddress: "काठमाडौं म.न.पा. ३, महाराजगञ्ज",
      province: "Bagmati",
      district: "Kathmandu",
      municipality: "Kathmandu",
      ward: "3",
      customerType: "Regular Customer",
      sourceId: "SRC-0005",
      pan: "",
      openingBalance: 0,
      creditLimit: 400000,
      notes: "VIP customer family.",
      status: "Active",
      createdAt: "2026-05-20"
    },
    {
      id: "CUS-0007",
      name: "Ramesh Adhikari",
      localName: "रमेश अधिकारी",
      mobile: "9841987654",
      altPhone: "",
      email: "ramesh.adh@nepal.test",
      address: "Kupondole-1, Lalitpur",
      localAddress: "ललितपुर म.न.पा. १, कुपण्डोल",
      province: "Bagmati",
      district: "Lalitpur",
      municipality: "Lalitpur",
      ward: "1",
      customerType: "Regular Customer",
      sourceId: "SRC-0001",
      pan: "605928172",
      openingBalance: 0,
      creditLimit: 300000,
      notes: "Walk-in repeat customer. Prefers 24K bullion coins.",
      status: "Active",
      createdAt: "2026-03-12"
    },
    {
      id: "CUS-0008",
      name: "Sunita Rai",
      localName: "सुनिता राई",
      mobile: "9818765432",
      altPhone: "",
      email: "sunita.rai@nepal.test",
      address: "Boudha-6, Kathmandu",
      localAddress: "काठमाडौं म.न.पा. ६, बौद्ध",
      province: "Bagmati",
      district: "Kathmandu",
      municipality: "Kathmandu",
      ward: "6",
      customerType: "Retail Customer",
      sourceId: "SRC-0009",
      pan: "",
      openingBalance: 0,
      creditLimit: 350000,
      notes: "Referred from Boudha counter.",
      status: "Active",
      createdAt: "2026-07-22"
    },
    {
      id: "CUS-0009",
      name: "Deepak Shrestha",
      localName: "दीपक श्रेष्ठ",
      mobile: "9851239876",
      altPhone: "01-6638210",
      email: "deepak.shrestha@nepal.test",
      address: "Thimi-4, Bhaktapur",
      localAddress: "मध्यपुर थिमी न.पा. ४, भक्तपुर",
      province: "Bagmati",
      district: "Bhaktapur",
      municipality: "Madhyapur Thimi",
      ward: "4",
      customerType: "Wholesale Customer",
      sourceId: "SRC-0006",
      pan: "601192837",
      openingBalance: 0,
      creditLimit: 1200000,
      notes: "Dealer partner for gold bangles.",
      status: "Active",
      createdAt: "2026-02-18"
    },
    {
      id: "CUS-0010",
      name: "Manoj Tamang",
      localName: "मनोज तामाङ",
      mobile: "9801234567",
      altPhone: "",
      email: "manoj.tamang@nepal.test",
      address: "Jorpati-5, Kathmandu",
      localAddress: "गोकर्णेश्वर न.पा. ५, जोरपाटी",
      province: "Bagmati",
      district: "Kathmandu",
      municipality: "Gokarneshwor",
      ward: "5",
      customerType: "Retail Customer",
      sourceId: "SRC-0001",
      pan: "",
      openingBalance: 0,
      creditLimit: 250000,
      notes: "Collateral khata transaction holder.",
      status: "Active",
      createdAt: "2026-06-15"
    },
    {
      id: "CUS-0011",
      name: "Pooja Joshi",
      localName: "पूजा जोशी",
      mobile: "9841334455",
      altPhone: "",
      email: "pooja.joshi@nepal.test",
      address: "Jawalakhel-4, Lalitpur",
      localAddress: "ललितपुर म.न.पा. ४, जावलाखेल",
      province: "Bagmati",
      district: "Lalitpur",
      municipality: "Lalitpur",
      ward: "4",
      customerType: "Corporate Customer",
      sourceId: "SRC-0008",
      pan: "608291029",
      openingBalance: 0,
      creditLimit: 500000,
      notes: "Corporate gifting contact for bank annual tokens.",
      status: "Active",
      createdAt: "2026-05-02"
    },
    {
      id: "CUS-0012",
      name: "Rajesh Khadka",
      localName: "राजेश खड्का",
      mobile: "9861998877",
      altPhone: "",
      email: "rajesh.khadka@nepal.test",
      address: "Kalanki-14, Kathmandu",
      localAddress: "काठमाडौं म.न.पा. १४, कलंकी",
      province: "Bagmati",
      district: "Kathmandu",
      municipality: "Kathmandu",
      ward: "14",
      customerType: "Regular Customer",
      sourceId: "SRC-0004",
      pan: "",
      openingBalance: 0,
      creditLimit: 300000,
      notes: "Regular family purchases.",
      status: "Active",
      createdAt: "2026-07-10"
    },
    {
      id: "CUS-0013",
      name: "Gita Bhandari",
      localName: "गीता भण्डारी",
      mobile: "9843667788",
      altPhone: "",
      email: "gita.bhandari@nepal.test",
      address: "Balaju-16, Kathmandu",
      localAddress: "काठमाडौं म.न.पा. १६, बालाजु",
      province: "Bagmati",
      district: "Kathmandu",
      municipality: "Kathmandu",
      ward: "16",
      customerType: "Retail Customer",
      sourceId: "SRC-0002",
      pan: "",
      openingBalance: 0,
      creditLimit: 200000,
      notes: "Gold locket and ring buyer.",
      status: "Active",
      createdAt: "2026-08-14"
    },
    {
      id: "CUS-0014",
      name: "Suresh Shrestha",
      localName: "सुरेश श्रेष्ठ",
      mobile: "9851122334",
      altPhone: "01-6610992",
      email: "suresh.shrestha@nepal.test",
      address: "Durbar Square-5, Bhaktapur",
      localAddress: "भक्तपुर न.पा. ५, दरबार क्षेत्र",
      province: "Bagmati",
      district: "Bhaktapur",
      municipality: "Bhaktapur",
      ward: "5",
      customerType: "Dealer",
      sourceId: "SRC-0007",
      pan: "600192831",
      openingBalance: 0,
      creditLimit: 2000000,
      notes: "Major silver utensil and gold reseller.",
      status: "Active",
      createdAt: "2026-01-20"
    },
    {
      id: "CUS-0015",
      name: "Kamala KC",
      localName: "कमला के.सी.",
      mobile: "9849001122",
      altPhone: "",
      email: "kamala.kc@nepal.test",
      address: "Imadol-8, Lalitpur",
      localAddress: "महालक्ष्मी न.पा. ८, इमाडोल, ललितपुर",
      province: "Bagmati",
      district: "Lalitpur",
      municipality: "Mahalaxmi",
      ward: "8",
      customerType: "Retail Customer",
      sourceId: "SRC-0006",
      pan: "",
      openingBalance: 0,
      creditLimit: 150000,
      notes: "Silver jewellery and 22K studs.",
      status: "Active",
      createdAt: "2026-08-28"
    },
    {
      id: "CUS-0016",
      name: "Pradeep Paudel",
      localName: "प्रदीप पौडेल",
      mobile: "9811445566",
      altPhone: "",
      email: "pradeep.paudel@nepal.test",
      address: "Dillibazar-33, Kathmandu",
      localAddress: "काठमाडौं म.न.पा. ३३, डिल्लीबजार",
      province: "Bagmati",
      district: "Kathmandu",
      municipality: "Kathmandu",
      ward: "33",
      customerType: "Retail Customer",
      sourceId: "SRC-0001",
      pan: "",
      openingBalance: 0,
      creditLimit: 300000,
      notes: "Wedding set buyer.",
      status: "Active",
      createdAt: "2026-09-02"
    }
  ],

  bills: [
    {
      id: "INV-2026-0001",
      billNumber: "INV-2026-0001",
      nepaliSerial: "१००१",
      billDate: "2026-09-15",
      dueDate: "2026-10-15",
      customerId: "CUS-0001",
      sourceId: "SRC-0001",
      salesperson: "Aarati Thapa",
      paymentTerms: "30 Days Khata",
      notes: "Bridal gold necklace order with stone accents",
      status: "Partially Paid",
      items: [
        {
          id: "ITM-001",
          name: "24K Gold Rani Haar (Necklace)",
          category: "Necklace",
          metal: "Gold",
          purity: "24K",
          unit: "Gram",
          grossWeight: 25.50,
          stoneWeight: 2.00,
          otherWeight: 0.00,
          netWeight: 23.50,
          rate: 19200, // Locked rate snapshot
          metalValue: 451200,
          makingCharge: 25000,
          wastagePercent: 8,
          wastageAmount: 36096,
          stoneCharge: 10000,
          otherCharge: 2000,
          discount: 5000,
          itemTotal: 519296,
          remarks: "Special filigree work"
        }
      ],
      oldGoldDeduction: {
        hasOldGold: false,
        item: "",
        purity: "",
        weight: 0,
        rate: 0,
        value: 0
      },
      subtotal: 519296,
      makingChargesTotal: 25000,
      wastageTotal: 36096,
      stoneChargesTotal: 10000,
      otherChargesTotal: 2000,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 519296,
      paidAmount: 269296,
      outstandingAmount: 250000,
      createdAt: "2026-09-15 10:30 AM",
      createdBy: "Aarati Thapa",
      updatedAt: "2026-09-15 10:45 AM",
      updatedBy: "Aarati Thapa"
    },
    {
      id: "INV-2026-0002",
      billNumber: "INV-2026-0002",
      nepaliSerial: "१००२",
      billDate: "2026-09-14",
      dueDate: "2026-09-14",
      customerId: "CUS-0002",
      sourceId: "SRC-0004",
      salesperson: "Subin Dhamala",
      paymentTerms: "Immediate Cash",
      notes: "Solitaire diamond ring & gold chain",
      status: "Paid",
      items: [
        {
          id: "ITM-002",
          name: "22K Gold Chain",
          category: "Chain",
          metal: "Gold",
          purity: "22K",
          unit: "Gram",
          grossWeight: 11.66, // 1 Tola approx
          stoneWeight: 0.00,
          otherWeight: 0.00,
          netWeight: 11.66,
          rate: 17600,
          metalValue: 205216,
          makingCharge: 12000,
          wastagePercent: 7,
          wastageAmount: 14365,
          stoneCharge: 0,
          otherCharge: 0,
          discount: 2500,
          itemTotal: 229081,
          remarks: "Handcrafted rope link"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 229081,
      makingChargesTotal: 12000,
      wastageTotal: 14365,
      stoneChargesTotal: 0,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 229081,
      paidAmount: 229081,
      outstandingAmount: 0,
      createdAt: "2026-09-14 02:15 PM",
      createdBy: "Subin Dhamala",
      updatedAt: "2026-09-14 02:20 PM",
      updatedBy: "Subin Dhamala"
    },
    {
      id: "INV-2026-0003",
      billNumber: "INV-2026-0003",
      nepaliSerial: "१००३",
      billDate: "2026-09-13",
      dueDate: "2026-10-13",
      customerId: "CUS-0003",
      sourceId: "SRC-0007",
      salesperson: "Sunil Shrestha",
      paymentTerms: "Dealer Credit 30 Days",
      notes: "Bulk gold bangles lot for wholesale supply",
      status: "Partially Paid",
      items: [
        {
          id: "ITM-003",
          name: "22K Plain Gold Bangles (Pair)",
          category: "Bangle",
          metal: "Gold",
          purity: "22K",
          unit: "Gram",
          grossWeight: 35.00,
          stoneWeight: 0.00,
          otherWeight: 0.00,
          netWeight: 35.00,
          rate: 17600,
          metalValue: 616000,
          makingCharge: 28000,
          wastagePercent: 6,
          wastageAmount: 36960,
          stoneCharge: 0,
          otherCharge: 0,
          discount: 10000,
          itemTotal: 670960,
          remarks: "Standard size 2.6"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 670960,
      makingChargesTotal: 28000,
      wastageTotal: 36960,
      stoneChargesTotal: 0,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 670960,
      paidAmount: 250960,
      outstandingAmount: 420000,
      createdAt: "2026-09-13 11:30 AM",
      createdBy: "Sunil Shrestha",
      updatedAt: "2026-09-13 12:00 PM",
      updatedBy: "Sunil Shrestha"
    },
    {
      id: "INV-2026-0004",
      billNumber: "INV-2026-0004",
      nepaliSerial: "१००४",
      billDate: "2026-09-12",
      dueDate: "2026-10-12",
      customerId: "CUS-0004",
      sourceId: "SRC-0002",
      salesperson: "Aarati Thapa",
      paymentTerms: "Partial advance paid via eSewa",
      notes: "Bridal Jhumka Earrings with ruby beads",
      status: "Partially Paid",
      items: [
        {
          id: "ITM-004",
          name: "24K Designer Jhumka Earrings",
          category: "Earring",
          metal: "Gold",
          purity: "24K",
          unit: "Gram",
          grossWeight: 14.50,
          stoneWeight: 1.20,
          otherWeight: 0.00,
          netWeight: 13.30,
          rate: 19200,
          metalValue: 255360,
          makingCharge: 18000,
          wastagePercent: 8,
          wastageAmount: 20428,
          stoneCharge: 4500,
          otherCharge: 0,
          discount: 3000,
          itemTotal: 295288,
          remarks: "Traditional Peacock carving"
        }
      ],
      oldGoldDeduction: {
        hasOldGold: true,
        item: "Old 22K Broken Ring",
        purity: "22K",
        weight: 6.5,
        rate: 16950,
        value: 110175
      },
      subtotal: 295288,
      makingChargesTotal: 18000,
      wastageTotal: 20428,
      stoneChargesTotal: 4500,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 185113, // 295288 - 110175 old gold
      paidAmount: 100113,
      outstandingAmount: 85000,
      createdAt: "2026-09-12 03:45 PM",
      createdBy: "Aarati Thapa",
      updatedAt: "2026-09-12 04:00 PM",
      updatedBy: "Aarati Thapa"
    },
    {
      id: "INV-2026-0005",
      billNumber: "INV-2026-0005",
      nepaliSerial: "१००५",
      billDate: "2026-09-11",
      dueDate: "2026-09-11",
      customerId: "CUS-0005",
      sourceId: "SRC-0003",
      salesperson: "Subin Dhamala",
      paymentTerms: "Full Paid by Card",
      notes: "Solitaire diamond ring in 18K white gold",
      status: "Paid",
      items: [
        {
          id: "ITM-005",
          name: "18K Diamond Solitaire Engagement Ring",
          category: "Ring",
          metal: "Gold",
          purity: "18K",
          unit: "Gram",
          grossWeight: 4.80,
          stoneWeight: 0.35,
          otherWeight: 0.00,
          netWeight: 4.45,
          rate: 14400,
          metalValue: 64080,
          makingCharge: 15000,
          wastagePercent: 5,
          wastageAmount: 3204,
          stoneCharge: 85000, // Diamond cost
          otherCharge: 1500, // Certification
          discount: 3784,
          itemTotal: 165000,
          remarks: "0.50 Carat VVS1 certified diamond"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 165000,
      makingChargesTotal: 15000,
      wastageTotal: 3204,
      stoneChargesTotal: 85000,
      otherChargesTotal: 1500,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 165000,
      paidAmount: 165000,
      outstandingAmount: 0,
      createdAt: "2026-09-11 01:20 PM",
      createdBy: "Subin Dhamala",
      updatedAt: "2026-09-11 01:25 PM",
      updatedBy: "Subin Dhamala"
    },
    {
      id: "INV-2026-0006",
      billNumber: "INV-2026-0006",
      nepaliSerial: "१००६",
      billDate: "2026-09-10",
      dueDate: "2026-10-10",
      customerId: "CUS-0006",
      sourceId: "SRC-0005",
      salesperson: "Sunil Shrestha",
      paymentTerms: "Partial payment bank transfer",
      notes: "Gold Mangalsutra set with black beads",
      status: "Partially Paid",
      items: [
        {
          id: "ITM-006",
          name: "24K Gold Mangalsutra Pendant & Chain",
          category: "Pendant",
          metal: "Gold",
          purity: "24K",
          unit: "Gram",
          grossWeight: 18.20,
          stoneWeight: 1.80,
          otherWeight: 0.00,
          netWeight: 16.40,
          rate: 19200,
          metalValue: 314880,
          makingCharge: 20000,
          wastagePercent: 8,
          wastageAmount: 25190,
          stoneCharge: 3500,
          otherCharge: 0,
          discount: 3570,
          itemTotal: 360000,
          remarks: "Traditional double-chain design"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 360000,
      makingChargesTotal: 20000,
      wastageTotal: 25190,
      stoneChargesTotal: 3500,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 360000,
      paidAmount: 210000,
      outstandingAmount: 150000,
      createdAt: "2026-09-10 11:00 AM",
      createdBy: "Sunil Shrestha",
      updatedAt: "2026-09-10 11:15 AM",
      updatedBy: "Sunil Shrestha"
    },
    {
      id: "INV-2026-0007",
      billNumber: "INV-2026-0007",
      nepaliSerial: "१००७",
      billDate: "2026-09-09",
      dueDate: "2026-09-09",
      customerId: "CUS-0007",
      sourceId: "SRC-0001",
      salesperson: "Aarati Thapa",
      paymentTerms: "Cash on counter",
      notes: "24K Pure Gold Minted Bullion Coin (1 Tola)",
      status: "Paid",
      items: [
        {
          id: "ITM-007",
          name: "24K Ganesh Laxmi Gold Coin (1 Tola)",
          category: "Coin",
          metal: "Gold",
          purity: "24K",
          unit: "Tola",
          grossWeight: 11.664,
          stoneWeight: 0,
          otherWeight: 0,
          netWeight: 11.664,
          rate: 19200,
          metalValue: 223949,
          makingCharge: 3000,
          wastagePercent: 0,
          wastageAmount: 0,
          stoneCharge: 0,
          otherCharge: 0,
          discount: 949,
          itemTotal: 226000,
          remarks: "99.9% fine hallmark mint"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 226000,
      makingChargesTotal: 3000,
      wastageTotal: 0,
      stoneChargesTotal: 0,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 226000,
      paidAmount: 226000,
      outstandingAmount: 0,
      createdAt: "2026-09-09 04:10 PM",
      createdBy: "Aarati Thapa",
      updatedAt: "2026-09-09 04:15 PM",
      updatedBy: "Aarati Thapa"
    },
    {
      id: "INV-2026-0008",
      billNumber: "INV-2026-0008",
      nepaliSerial: "१००८",
      billDate: "2026-09-08",
      dueDate: "2026-10-08",
      customerId: "CUS-0008",
      sourceId: "SRC-0009",
      salesperson: "Subin Dhamala",
      paymentTerms: "Khata terms pending payment",
      notes: "Bridal choker set in 22K Gold",
      status: "Unpaid",
      items: [
        {
          id: "ITM-008",
          name: "22K Traditional Bridal Choker",
          category: "Necklace",
          metal: "Gold",
          purity: "22K",
          unit: "Gram",
          grossWeight: 18.00,
          stoneWeight: 1.50,
          otherWeight: 0.00,
          netWeight: 16.50,
          rate: 17600,
          metalValue: 290400,
          makingCharge: 18000,
          wastagePercent: 7,
          wastageAmount: 20328,
          stoneCharge: 3000,
          otherCharge: 0,
          discount: 1728,
          itemTotal: 310000,
          remarks: "Custom length with thread dori"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 310000,
      makingChargesTotal: 18000,
      wastageTotal: 20328,
      stoneChargesTotal: 3000,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 310000,
      paidAmount: 0,
      outstandingAmount: 310000,
      createdAt: "2026-09-08 01:15 PM",
      createdBy: "Subin Dhamala",
      updatedAt: "2026-09-08 01:15 PM",
      updatedBy: "Subin Dhamala"
    },
    {
      id: "INV-2026-0009",
      billNumber: "INV-2026-0009",
      nepaliSerial: "१००९",
      billDate: "2026-09-05",
      dueDate: "2026-10-05",
      customerId: "CUS-0009",
      sourceId: "SRC-0006",
      salesperson: "Sunil Shrestha",
      paymentTerms: "Wholesale credit",
      notes: "Gold bracelets collection",
      status: "Partially Paid",
      items: [
        {
          id: "ITM-009",
          name: "22K Gents Gold Kada (Bracelet)",
          category: "Bracelet",
          metal: "Gold",
          purity: "22K",
          unit: "Gram",
          grossWeight: 52.00,
          stoneWeight: 0.00,
          otherWeight: 0.00,
          netWeight: 52.00,
          rate: 17600,
          metalValue: 915200,
          makingCharge: 40000,
          wastagePercent: 6,
          wastageAmount: 54912,
          stoneCharge: 0,
          otherCharge: 0,
          discount: 10112,
          itemTotal: 1000000,
          remarks: "Heavy solid core kada"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 1000000,
      makingChargesTotal: 40000,
      wastageTotal: 54912,
      stoneChargesTotal: 0,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 1000000,
      paidAmount: 380000,
      outstandingAmount: 620000,
      createdAt: "2026-09-05 11:45 AM",
      createdBy: "Sunil Shrestha",
      updatedAt: "2026-09-05 12:30 PM",
      updatedBy: "Sunil Shrestha"
    },
    {
      id: "INV-2026-0010",
      billNumber: "INV-2026-0010",
      nepaliSerial: "१०१०",
      billDate: "2026-08-10",
      dueDate: "2026-09-10",
      customerId: "CUS-0010",
      sourceId: "SRC-0001",
      salesperson: "Subin Dhamala",
      paymentTerms: "भाखा पत्र (Pledge Khata terms 30 days)",
      notes: "Traditional Bhaka Patra transaction. Gold necklace pledge/purchase.",
      status: "Overdue",
      items: [
        {
          id: "ITM-010",
          name: "24K Gold Tilhari Necklace Set",
          category: "Necklace",
          metal: "Gold",
          purity: "24K",
          unit: "Gram",
          grossWeight: 15.80,
          stoneWeight: 0.80,
          otherWeight: 0.00,
          netWeight: 15.00,
          rate: 18200, // Historical rate from Aug 15
          metalValue: 273000,
          makingCharge: 16000,
          wastagePercent: 8,
          wastageAmount: 21840,
          stoneCharge: 2500,
          otherCharge: 0,
          discount: 3340,
          itemTotal: 310000,
          remarks: "Green pote stringing included"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 310000,
      makingChargesTotal: 16000,
      wastageTotal: 21840,
      stoneChargesTotal: 2500,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 310000,
      paidAmount: 130000,
      outstandingAmount: 180000,
      createdAt: "2026-08-10 10:20 AM",
      createdBy: "Subin Dhamala",
      updatedAt: "2026-08-10 10:35 AM",
      updatedBy: "Subin Dhamala"
    },
    {
      id: "INV-2026-0011",
      billNumber: "INV-2026-0011",
      nepaliSerial: "१०११",
      billDate: "2026-09-02",
      dueDate: "2026-09-02",
      customerId: "CUS-0011",
      sourceId: "SRC-0008",
      salesperson: "Subin Dhamala",
      paymentTerms: "Corporate Bank Transfer",
      notes: "Corporate silver commemorative bowls for anniversary",
      status: "Paid",
      items: [
        {
          id: "ITM-011",
          name: "Silver Chandi Puja Bowls (Set of 10)",
          category: "Other",
          metal: "Silver",
          purity: "Fine (99.9%)",
          unit: "Gram",
          grossWeight: 450.00,
          stoneWeight: 0.00,
          otherWeight: 0.00,
          netWeight: 450.00,
          rate: 250,
          metalValue: 112500,
          makingCharge: 18000,
          wastagePercent: 4,
          wastageAmount: 4500,
          stoneCharge: 0,
          otherCharge: 0,
          discount: 5000,
          itemTotal: 130000,
          remarks: "Custom bank logo engraved"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 130000,
      makingChargesTotal: 18000,
      wastageTotal: 4500,
      stoneChargesTotal: 0,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 130000,
      paidAmount: 130000,
      outstandingAmount: 0,
      createdAt: "2026-09-02 02:00 PM",
      createdBy: "Subin Dhamala",
      updatedAt: "2026-09-02 02:30 PM",
      updatedBy: "Subin Dhamala"
    },
    {
      id: "INV-2026-0012",
      billNumber: "INV-2026-0012",
      nepaliSerial: "१०१२",
      billDate: "2026-09-01",
      dueDate: "2026-10-01",
      customerId: "CUS-0012",
      sourceId: "SRC-0004",
      salesperson: "Aarati Thapa",
      paymentTerms: "Partial cash balance khata",
      notes: "22K Gold Ladies Ring",
      status: "Partially Paid",
      items: [
        {
          id: "ITM-0012",
          name: "22K Floral Ladies Ring",
          category: "Ring",
          metal: "Gold",
          purity: "22K",
          unit: "Gram",
          grossWeight: 7.20,
          stoneWeight: 0.40,
          otherWeight: 0.00,
          netWeight: 6.80,
          rate: 16950,
          metalValue: 115260,
          makingCharge: 8000,
          wastagePercent: 7,
          wastageAmount: 8068,
          stoneCharge: 1500,
          otherCharge: 0,
          discount: 2828,
          itemTotal: 130000,
          remarks: "Size 14 Nepali"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 130000,
      makingChargesTotal: 8000,
      wastageTotal: 8068,
      stoneChargesTotal: 1500,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 130000,
      paidAmount: 35000,
      outstandingAmount: 95000,
      createdAt: "2026-09-01 11:20 AM",
      createdBy: "Aarati Thapa",
      updatedAt: "2026-09-01 11:30 AM",
      updatedBy: "Aarati Thapa"
    },
    {
      id: "INV-2026-0013",
      billNumber: "INV-2026-0013",
      nepaliSerial: "१०१३",
      billDate: "2026-08-25",
      dueDate: "2026-08-25",
      customerId: "CUS-0013",
      sourceId: "SRC-0002",
      salesperson: "Sunil Shrestha",
      paymentTerms: "Full Paid QR Fonepay",
      notes: "Silver Payal / Kalli anklets",
      status: "Paid",
      items: [
        {
          id: "ITM-013",
          name: "Traditional Silver Bridal Payal (Pair)",
          category: "Bracelet",
          metal: "Silver",
          purity: "Fine (99.9%)",
          unit: "Gram",
          grossWeight: 120.00,
          stoneWeight: 0.00,
          otherWeight: 0.00,
          netWeight: 120.00,
          rate: 245,
          metalValue: 29400,
          makingCharge: 6500,
          wastagePercent: 5,
          wastageAmount: 1470,
          stoneCharge: 0,
          otherCharge: 0,
          discount: 1370,
          itemTotal: 36000,
          remarks: "Hand made silver bells"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 36000,
      makingChargesTotal: 6500,
      wastageTotal: 1470,
      stoneChargesTotal: 0,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 36000,
      paidAmount: 36000,
      outstandingAmount: 0,
      createdAt: "2026-08-25 04:00 PM",
      createdBy: "Sunil Shrestha",
      updatedAt: "2026-08-25 04:05 PM",
      updatedBy: "Sunil Shrestha"
    },
    {
      id: "INV-2026-0014",
      billNumber: "INV-2026-0014",
      nepaliSerial: "१०१४",
      billDate: "2026-08-20",
      dueDate: "2026-09-20",
      customerId: "CUS-0014",
      sourceId: "SRC-0007",
      salesperson: "Subin Dhamala",
      paymentTerms: "Wholesale 30 days dealer terms",
      notes: "Bulk gold chains for showroom consignment",
      status: "Partially Paid",
      items: [
        {
          id: "ITM-014",
          name: "22K Box Chains Assorted (5 Pcs)",
          category: "Chain",
          metal: "Gold",
          purity: "22K",
          unit: "Gram",
          grossWeight: 75.00,
          stoneWeight: 0.00,
          otherWeight: 0.00,
          netWeight: 75.00,
          rate: 16950,
          metalValue: 1271250,
          makingCharge: 55000,
          wastagePercent: 6,
          wastageAmount: 76275,
          stoneCharge: 0,
          otherCharge: 0,
          discount: 22525,
          itemTotal: 1380000,
          remarks: "Assorted 18 inch and 20 inch lengths"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 1380000,
      makingChargesTotal: 55000,
      wastageTotal: 76275,
      stoneChargesTotal: 0,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 1380000,
      paidAmount: 530000,
      outstandingAmount: 850000,
      createdAt: "2026-08-20 01:30 PM",
      createdBy: "Subin Dhamala",
      updatedAt: "2026-08-20 02:00 PM",
      updatedBy: "Subin Dhamala"
    },
    {
      id: "INV-2026-0015",
      billNumber: "INV-2026-0015",
      nepaliSerial: "१०१५",
      billDate: "2026-08-18",
      dueDate: "2026-09-18",
      customerId: "CUS-0015",
      sourceId: "SRC-0006",
      salesperson: "Aarati Thapa",
      paymentTerms: "Advance cash paid",
      notes: "22K Gold Stud Earrings",
      status: "Partially Paid",
      items: [
        {
          id: "ITM-015",
          name: "22K Topi Stud Earrings (Daily Wear)",
          category: "Earring",
          metal: "Gold",
          purity: "22K",
          unit: "Gram",
          grossWeight: 4.80,
          stoneWeight: 0.00,
          otherWeight: 0.00,
          netWeight: 4.80,
          rate: 16950,
          metalValue: 81360,
          makingCharge: 6000,
          wastagePercent: 7,
          wastageAmount: 5695,
          stoneCharge: 0,
          otherCharge: 0,
          discount: 1055,
          itemTotal: 92000,
          remarks: "Secure screw back"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 92000,
      makingChargesTotal: 6000,
      wastageTotal: 5695,
      stoneChargesTotal: 0,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 92000,
      paidAmount: 47000,
      outstandingAmount: 45000,
      createdAt: "2026-08-18 03:20 PM",
      createdBy: "Aarati Thapa",
      updatedAt: "2026-08-18 03:30 PM",
      updatedBy: "Aarati Thapa"
    },
    {
      id: "INV-2026-0016",
      billNumber: "INV-2026-0016",
      nepaliSerial: "१०१६",
      billDate: "2026-08-15",
      dueDate: "2026-08-15",
      customerId: "CUS-0016",
      sourceId: "SRC-0001",
      salesperson: "Subin Dhamala",
      paymentTerms: "Full Paid Cheque",
      notes: "Wedding Jewellery Package",
      status: "Paid",
      items: [
        {
          id: "ITM-016",
          name: "24K Bridal Full Set (Necklace, Bangles, Earrings)",
          category: "Necklace",
          metal: "Gold",
          purity: "24K",
          unit: "Gram",
          grossWeight: 60.00,
          stoneWeight: 3.50,
          otherWeight: 0.00,
          netWeight: 56.50,
          rate: 18200,
          metalValue: 1028300,
          makingCharge: 60000,
          wastagePercent: 8,
          wastageAmount: 82264,
          stoneCharge: 12000,
          otherCharge: 0,
          discount: 22564,
          itemTotal: 1160000,
          remarks: "Delivered in red velvet presentation box"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 1160000,
      makingChargesTotal: 60000,
      wastageTotal: 82264,
      stoneChargesTotal: 12000,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 1160000,
      paidAmount: 1160000,
      outstandingAmount: 0,
      createdAt: "2026-08-15 11:00 AM",
      createdBy: "Subin Dhamala",
      updatedAt: "2026-08-15 11:30 AM",
      updatedBy: "Subin Dhamala"
    },
    {
      id: "INV-2026-0017",
      billNumber: "INV-2026-0017",
      nepaliSerial: "१०१७",
      billDate: "2026-08-05",
      dueDate: "2026-08-05",
      customerId: "CUS-0001",
      sourceId: "SRC-0001",
      salesperson: "Aarati Thapa",
      paymentTerms: "Cancelled order",
      notes: "Customer decided on custom weight redesign",
      status: "Cancelled",
      cancellationReason: "Design specification changed by client",
      cancelledBy: "Subin Dhamala",
      cancelledAt: "2026-08-06 10:00 AM",
      items: [
        {
          id: "ITM-017",
          name: "22K Bangle Sample",
          category: "Bangle",
          metal: "Gold",
          purity: "22K",
          unit: "Gram",
          grossWeight: 20.00,
          stoneWeight: 0.00,
          otherWeight: 0.00,
          netWeight: 20.00,
          rate: 16950,
          metalValue: 339000,
          makingCharge: 15000,
          wastagePercent: 7,
          wastageAmount: 23730,
          stoneCharge: 0,
          otherCharge: 0,
          discount: 2730,
          itemTotal: 375000,
          remarks: "Cancelled"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 375000,
      grandTotal: 375000,
      paidAmount: 0,
      outstandingAmount: 0,
      createdAt: "2026-08-05 03:00 PM",
      createdBy: "Aarati Thapa",
      updatedAt: "2026-08-06 10:00 AM",
      updatedBy: "Subin Dhamala"
    },
    {
      id: "INV-2026-0018",
      billNumber: "INV-2026-0018",
      nepaliSerial: "१०१८",
      billDate: "2026-09-15",
      dueDate: "2026-09-15",
      customerId: "CUS-0007",
      sourceId: "SRC-0001",
      salesperson: "Aarati Thapa",
      paymentTerms: "Cash Paid",
      notes: "Silver Lakshmi Ganesh Idol",
      status: "Paid",
      items: [
        {
          id: "ITM-018",
          name: "Fine Silver Pooja Murti Idol",
          category: "Other",
          metal: "Silver",
          purity: "Fine (99.9%)",
          unit: "Gram",
          grossWeight: 210.00,
          stoneWeight: 0.00,
          otherWeight: 0.00,
          netWeight: 210.00,
          rate: 250,
          metalValue: 52500,
          makingCharge: 12000,
          wastagePercent: 4,
          wastageAmount: 2100,
          stoneCharge: 0,
          otherCharge: 0,
          discount: 1600,
          itemTotal: 65000,
          remarks: "Antique silver polish"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 65000,
      makingChargesTotal: 12000,
      wastageTotal: 2100,
      stoneChargesTotal: 0,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 65000,
      paidAmount: 65000,
      outstandingAmount: 0,
      createdAt: "2026-09-15 11:30 AM",
      createdBy: "Aarati Thapa",
      updatedAt: "2026-09-15 11:35 AM",
      updatedBy: "Aarati Thapa"
    },
    {
      id: "INV-2026-0019",
      billNumber: "INV-2026-0019",
      nepaliSerial: "१०१९",
      billDate: "2026-09-15",
      dueDate: "2026-10-15",
      customerId: "CUS-0002",
      sourceId: "SRC-0004",
      salesperson: "Subin Dhamala",
      paymentTerms: "Draft Order",
      notes: "Estimate for upcoming Dashain festive purchase",
      status: "Draft",
      items: [
        {
          id: "ITM-019",
          name: "24K Gold Navaratna Pendant",
          category: "Pendant",
          metal: "Gold",
          purity: "24K",
          unit: "Gram",
          grossWeight: 10.50,
          stoneWeight: 1.50,
          otherWeight: 0.00,
          netWeight: 9.00,
          rate: 19200,
          metalValue: 172800,
          makingCharge: 14000,
          wastagePercent: 8,
          wastageAmount: 13824,
          stoneCharge: 18000,
          otherCharge: 0,
          discount: 3624,
          itemTotal: 215000,
          remarks: "9 natural astrological gemstones"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 215000,
      makingChargesTotal: 14000,
      wastageTotal: 13824,
      stoneChargesTotal: 18000,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 215000,
      paidAmount: 0,
      outstandingAmount: 215000,
      createdAt: "2026-09-15 01:10 PM",
      createdBy: "Subin Dhamala",
      updatedAt: "2026-09-15 01:10 PM",
      updatedBy: "Subin Dhamala"
    },
    {
      id: "INV-2026-0020",
      billNumber: "INV-2026-0020",
      nepaliSerial: "१०२०",
      billDate: "2026-09-14",
      dueDate: "2026-09-14",
      customerId: "CUS-0005",
      sourceId: "SRC-0003",
      salesperson: "Sunil Shrestha",
      paymentTerms: "Paid in full via Bank Transfer",
      notes: "Custom Platinum Men Band",
      status: "Paid",
      items: [
        {
          id: "ITM-020",
          name: "Platinum 950 Brushed Wedding Band",
          category: "Ring",
          metal: "Platinum",
          purity: "Pt 950",
          unit: "Gram",
          grossWeight: 8.50,
          stoneWeight: 0.00,
          otherWeight: 0.00,
          netWeight: 8.50,
          rate: 7500,
          metalValue: 63750,
          makingCharge: 14000,
          wastagePercent: 4,
          wastageAmount: 2550,
          stoneCharge: 0,
          otherCharge: 0,
          discount: 300,
          itemTotal: 80000,
          remarks: "Comfort fit engraving"
        }
      ],
      oldGoldDeduction: { hasOldGold: false },
      subtotal: 80000,
      makingChargesTotal: 14000,
      wastageTotal: 2550,
      stoneChargesTotal: 0,
      otherChargesTotal: 0,
      billDiscount: 0,
      taxPercent: 0,
      taxAmount: 0,
      grandTotal: 80000,
      paidAmount: 80000,
      outstandingAmount: 0,
      createdAt: "2026-09-14 04:30 PM",
      createdBy: "Sunil Shrestha",
      updatedAt: "2026-09-14 04:40 PM",
      updatedBy: "Sunil Shrestha"
    }
  ],

  payments: [
    {
      id: "PAY-0001",
      billId: "INV-2026-0001",
      billNumber: "INV-2026-0001",
      customerId: "CUS-0001",
      customerName: "Ram Sharma",
      paymentDate: "2026-09-15",
      paymentMethod: "Cash",
      amount: 150000,
      referenceNumber: "CASH-REC-101",
      receivedBy: "Aarati Thapa",
      notes: "Advance cash payment on counter",
      status: "Success",
      createdAt: "2026-09-15 10:40 AM"
    },
    {
      id: "PAY-0002",
      billId: "INV-2026-0001",
      billNumber: "INV-2026-0001",
      customerId: "CUS-0001",
      customerName: "Ram Sharma",
      paymentDate: "2026-09-15",
      paymentMethod: "QR",
      amount: 119296,
      referenceNumber: "FONEPAY-982138",
      receivedBy: "Aarati Thapa",
      notes: "QR payment via eSewa / Fonepay",
      status: "Success",
      createdAt: "2026-09-15 10:45 AM"
    },
    {
      id: "PAY-0003",
      billId: "INV-2026-0002",
      billNumber: "INV-2026-0002",
      customerId: "CUS-0002",
      customerName: "Sita Shrestha",
      paymentDate: "2026-09-14",
      paymentMethod: "Cash",
      amount: 229081,
      referenceNumber: "CASH-REC-102",
      receivedBy: "Subin Dhamala",
      notes: "Full settlement on purchase",
      status: "Success",
      createdAt: "2026-09-14 02:20 PM"
    },
    {
      id: "PAY-0004",
      billId: "INV-2026-0003",
      billNumber: "INV-2026-0003",
      customerId: "CUS-0003",
      customerName: "Hari Prasad Acharya",
      paymentDate: "2026-09-13",
      paymentMethod: "Bank Transfer",
      amount: 250960,
      referenceNumber: "NABIL-TX-882190",
      receivedBy: "Sunil Shrestha",
      notes: "Dealer advance transfer",
      status: "Success",
      createdAt: "2026-09-13 12:00 PM"
    },
    {
      id: "PAY-0005",
      billId: "INV-2026-0004",
      billNumber: "INV-2026-0004",
      customerId: "CUS-0004",
      customerName: "Mina Gurung",
      paymentDate: "2026-09-12",
      paymentMethod: "QR",
      amount: 100113,
      referenceNumber: "KHALTI-TX-5512",
      receivedBy: "Aarati Thapa",
      notes: "Khalti instant QR payment",
      status: "Success",
      createdAt: "2026-09-12 04:00 PM"
    },
    {
      id: "PAY-0006",
      billId: "INV-2026-0005",
      billNumber: "INV-2026-0005",
      customerId: "CUS-0005",
      customerName: "Bikash Thapa",
      paymentDate: "2026-09-11",
      paymentMethod: "Card",
      amount: 165000,
      referenceNumber: "POS-VISA-99120",
      receivedBy: "Subin Dhamala",
      notes: "Debit card POS transaction",
      status: "Success",
      createdAt: "2026-09-11 01:25 PM"
    },
    {
      id: "PAY-0007",
      billId: "INV-2026-0006",
      billNumber: "INV-2026-0006",
      customerId: "CUS-0006",
      customerName: "Anita Karki",
      paymentDate: "2026-09-10",
      paymentMethod: "Bank Transfer",
      amount: 210000,
      referenceNumber: "NIC-ASIA-77189",
      receivedBy: "Sunil Shrestha",
      notes: "ConnectIPS transfer",
      status: "Success",
      createdAt: "2026-09-10 11:15 AM"
    },
    {
      id: "PAY-0008",
      billId: "INV-2026-0007",
      billNumber: "INV-2026-0007",
      customerId: "CUS-0007",
      customerName: "Ramesh Adhikari",
      paymentDate: "2026-09-09",
      paymentMethod: "Cash",
      amount: 226000,
      referenceNumber: "CASH-REC-103",
      receivedBy: "Aarati Thapa",
      notes: "Full coin settlement",
      status: "Success",
      createdAt: "2026-09-09 04:15 PM"
    },
    {
      id: "PAY-0009",
      billId: "INV-2026-0009",
      billNumber: "INV-2026-0009",
      customerId: "CUS-0009",
      customerName: "Deepak Shrestha",
      paymentDate: "2026-09-05",
      paymentMethod: "Bank Transfer",
      amount: 380000,
      referenceNumber: "GLOBAL-IME-4412",
      receivedBy: "Sunil Shrestha",
      notes: "First installment bank transfer",
      status: "Success",
      createdAt: "2026-09-05 12:30 PM"
    },
    {
      id: "PAY-0010",
      billId: "INV-2026-0010",
      billNumber: "INV-2026-0010",
      customerId: "CUS-0010",
      customerName: "Manoj Tamang",
      paymentDate: "2026-08-10",
      paymentMethod: "Cash",
      amount: 130000,
      referenceNumber: "CASH-REC-088",
      receivedBy: "Subin Dhamala",
      notes: "Bhaka advance payment received",
      status: "Success",
      createdAt: "2026-08-10 10:35 AM"
    },
    {
      id: "PAY-0011",
      billId: "INV-2026-0011",
      billNumber: "INV-2026-0011",
      customerId: "CUS-0011",
      customerName: "Pooja Joshi",
      paymentDate: "2026-09-02",
      paymentMethod: "Bank Transfer",
      amount: 130000,
      referenceNumber: "CORP-TX-9901",
      receivedBy: "Subin Dhamala",
      notes: "Full institutional payment",
      status: "Success",
      createdAt: "2026-09-02 02:30 PM"
    },
    {
      id: "PAY-0012",
      billId: "INV-2026-0012",
      billNumber: "INV-2026-0012",
      customerId: "CUS-0012",
      customerName: "Rajesh Khadka",
      paymentDate: "2026-09-01",
      paymentMethod: "Cash",
      amount: 35000,
      referenceNumber: "CASH-REC-095",
      receivedBy: "Aarati Thapa",
      notes: "Cash advance for ring",
      status: "Success",
      createdAt: "2026-09-01 11:30 AM"
    },
    {
      id: "PAY-0013",
      billId: "INV-2026-0013",
      billNumber: "INV-2026-0013",
      customerId: "CUS-0013",
      customerName: "Gita Bhandari",
      paymentDate: "2026-08-25",
      paymentMethod: "QR",
      amount: 36000,
      referenceNumber: "FONEPAY-7721",
      receivedBy: "Sunil Shrestha",
      notes: "Payal full QR",
      status: "Success",
      createdAt: "2026-08-25 04:05 PM"
    },
    {
      id: "PAY-0014",
      billId: "INV-2026-0014",
      billNumber: "INV-2026-0014",
      customerId: "CUS-0014",
      customerName: "Suresh Shrestha",
      paymentDate: "2026-08-20",
      paymentMethod: "Cheque",
      amount: 530000,
      referenceNumber: "CHQ-EVEREST-88192",
      receivedBy: "Subin Dhamala",
      notes: "Cleared dealer cheque",
      status: "Success",
      createdAt: "2026-08-20 02:00 PM"
    },
    {
      id: "PAY-0015",
      billId: "INV-2026-0015",
      billNumber: "INV-2026-0015",
      customerId: "CUS-0015",
      customerName: "Kamala KC",
      paymentDate: "2026-08-18",
      paymentMethod: "Cash",
      amount: 47000,
      referenceNumber: "CASH-REC-077",
      receivedBy: "Aarati Thapa",
      notes: "Cash part payment",
      status: "Success",
      createdAt: "2026-08-18 03:30 PM"
    },
    {
      id: "PAY-0016",
      billId: "INV-2026-0016",
      billNumber: "INV-2026-0016",
      customerId: "CUS-0016",
      customerName: "Pradeep Paudel",
      paymentDate: "2026-08-15",
      paymentMethod: "Cheque",
      amount: 1160000,
      referenceNumber: "CHQ-NABIL-1029",
      receivedBy: "Subin Dhamala",
      notes: "Cleared wedding cheque",
      status: "Success",
      createdAt: "2026-08-15 11:30 AM"
    },
    {
      id: "PAY-0017",
      billId: "INV-2026-0018",
      billNumber: "INV-2026-0018",
      customerId: "CUS-0007",
      customerName: "Ramesh Adhikari",
      paymentDate: "2026-09-15",
      paymentMethod: "Cash",
      amount: 65000,
      referenceNumber: "CASH-REC-104",
      receivedBy: "Aarati Thapa",
      notes: "Full payment for idol",
      status: "Success",
      createdAt: "2026-09-15 11:35 AM"
    },
    {
      id: "PAY-0018",
      billId: "INV-2026-0020",
      billNumber: "INV-2026-0020",
      customerId: "CUS-0005",
      customerName: "Bikash Thapa",
      paymentDate: "2026-09-14",
      paymentMethod: "Bank Transfer",
      amount: 80000,
      referenceNumber: "NABIL-TX-3321",
      receivedBy: "Sunil Shrestha",
      notes: "Platinum ring payment",
      status: "Success",
      createdAt: "2026-09-14 04:40 PM"
    }
  ],

  // Traditional Nepali Khata Template Configuration (customizable in Template Builder)
  khataTemplate: {
    title: "भाखा पत्र",
    alternativeTitle: "पारम्परिक सुनचाँदी खता तथा बिल",
    showLegalDeclaration: true,
    legalDeclarationText: "लिखितम् {district} जिल्ला {localAddress} बस्ने म {customerName} आगे । मैले आजको मितिमा तपाईं काठमाडौं जिल्ला काठमाडौं म.न.पा. वडा नं. २२, न्युरोडमा {businessName} सञ्चालन गरी बस्ने {proprietor}सँग मैले, घर खर्च गर्न / व्यापार गर्न तपसिलमा लेखिएको अनुसारको रुपैयाँ लिएको ठीक साँचो हो । सो रुपैयाँको साँवा, ब्याज निम्न भाखा मिति भित्रमा चुक्ता पारी बुझाई धितो लिखनी लानेछु । भाखा भित्रमा साँवा ब्याज अडकाई नतिरे, नबिखनेमा धितो राखेको वस्तुमा मेरो हकदाबी रहने छैन र बाँकी छ भनि दावी पनि गर्ने छैन । गरे यसै लिखतले बदर गरीदिनु । धितो वस्तु आफ्नो जानी चलन गर्नु भनि मेरो मञ्जुरीबाट तपाईंको {businessName}, न्युरोड, काठमाडौंमा बसी यो धितो भाखा पत्र कागज लेखि सहीछाप गरी तपाईं {proprietor}लाई दिएँ ।",
    tapasilaHeader: "तपसिल",
    serialPrefix: "",
    fields: [
      { id: "f_sn", label: "क्र.सं.", originalKey: "sn", enabled: true, width: "6%" },
      { id: "f_desc", label: "धितो राखेको विवरण / सामानको विवरण", originalKey: "desc", enabled: true, width: "36%" },
      { id: "f_weight", label: "तौल (ग्रा./तोला)", originalKey: "weight", enabled: true, width: "12%" },
      { id: "f_pcs", label: "थान", originalKey: "pcs", enabled: true, width: "8%" },
      { id: "f_total", label: "जोर / जम्मा", originalKey: "total", enabled: true, width: "14%" },
      { id: "f_debit", label: "दा (डेबिट / लिने)", originalKey: "debit", enabled: true, width: "12%" },
      { id: "f_credit", label: "बा (क्रेडिट / बाँकी)", originalKey: "credit", enabled: true, width: "12%" }
    ],
    showCustomerPhone: true,
    showSignature: true,
    showPreparedBy: true,
    interestMonthlyPercent: 1.5,
    fontFamily: "Noto Sans Devanagari"
  },

  auditLogs: [
    {
      id: "AUD-001",
      timestamp: "2026-09-15 09:30 AM",
      userId: "USR-001",
      userName: "Subin Dhamala (Admin)",
      module: "Metal Rates",
      action: "Rate Verified",
      recordId: "RATE-001",
      description: "Gold 24K rate verified at NPR 19,200/g per FENEGOSIDA morning publication",
      oldValue: "NPR 18,500/g",
      newValue: "NPR 19,200/g"
    },
    {
      id: "AUD-002",
      timestamp: "2026-09-15 10:30 AM",
      userId: "USR-004",
      userName: "Aarati Thapa (Cashier)",
      module: "Billing",
      action: "Bill Created",
      recordId: "INV-2026-0001",
      description: "Created new bill INV-2026-0001 for Ram Sharma with 24K Rani Haar",
      oldValue: "-",
      newValue: "NPR 519,296"
    },
    {
      id: "AUD-003",
      timestamp: "2026-09-15 10:40 AM",
      userId: "USR-004",
      userName: "Aarati Thapa (Cashier)",
      module: "Payments",
      action: "Payment Recorded",
      recordId: "PAY-0001",
      description: "Cash advance payment of NPR 150,000 received for INV-2026-0001",
      oldValue: "NPR 0",
      newValue: "NPR 150,000"
    },
    {
      id: "AUD-004",
      timestamp: "2026-09-15 10:45 AM",
      userId: "USR-004",
      userName: "Aarati Thapa (Cashier)",
      module: "Payments",
      action: "Payment Recorded",
      recordId: "PAY-0002",
      description: "QR eSewa payment of NPR 119,296 received for INV-2026-0001. Outstanding NPR 250,000.",
      oldValue: "NPR 150,000",
      newValue: "NPR 269,296"
    },
    {
      id: "AUD-005",
      timestamp: "2026-09-14 02:15 PM",
      userId: "USR-001",
      userName: "Subin Dhamala (Admin)",
      module: "Billing",
      action: "Bill Confirmed",
      recordId: "INV-2026-0002",
      description: "Confirmed bill INV-2026-0002 for Sita Shrestha. Gold 22K rate locked at NPR 17,600/g.",
      oldValue: "Draft",
      newValue: "Paid"
    },
    {
      id: "AUD-006",
      timestamp: "2026-09-13 11:30 AM",
      userId: "USR-003",
      userName: "Sunil Shrestha (Accountant)",
      module: "Billing",
      action: "Bill Created",
      recordId: "INV-2026-0003",
      description: "Wholesale gold bangles bill created for Hari Prasad Acharya",
      oldValue: "-",
      newValue: "NPR 670,960"
    },
    {
      id: "AUD-007",
      timestamp: "2026-09-12 04:00 PM",
      userId: "USR-004",
      userName: "Aarati Thapa (Cashier)",
      module: "Old Gold",
      action: "Exchange Adjusted",
      recordId: "INV-2026-0004",
      description: "Old 22K gold ring 6.5g traded in for NPR 110,175 value deduction",
      oldValue: "NPR 0",
      newValue: "NPR 110,175"
    },
    {
      id: "AUD-008",
      timestamp: "2026-08-06 10:00 AM",
      userId: "USR-001",
      userName: "Subin Dhamala (Admin)",
      module: "Billing",
      action: "Bill Cancelled",
      recordId: "INV-2026-0017",
      description: "Bill INV-2026-0017 cancelled due to client design weight specification redesign",
      oldValue: "Confirmed",
      newValue: "Cancelled"
    }
  ],

  notifications: [
    {
      id: "NOTIF-001",
      title: "Today's Gold Rate Verified",
      message: "Gold 24K rate set to NPR 19,200/g by Subin Dhamala",
      time: "15 Sep, 09:30 AM",
      type: "success",
      read: false
    },
    {
      id: "NOTIF-002",
      title: "Overdue Bhaka Alert",
      message: "Customer Manoj Tamang (INV-2026-0010) has NPR 180,000 overdue for 35 days",
      time: "15 Sep, 08:00 AM",
      type: "danger",
      read: false
    },
    {
      id: "NOTIF-003",
      title: "Large Outstanding Balance",
      message: "Dealer Suresh Shrestha has total outstanding of NPR 850,000",
      time: "14 Sep, 05:00 PM",
      type: "warning",
      read: false
    },
    {
      id: "NOTIF-004",
      title: "New Customer Registered",
      message: "Pradeep Paudel added via Walk-in New Road counter",
      time: "14 Sep, 02:00 PM",
      type: "info",
      read: true
    }
  ],

  settings: {
    metalPurities: [
      { metal: "Gold", purity: "24K", fineness: 0.999, description: "Fine Hallmark 99.9%" },
      { metal: "Gold", purity: "22K", fineness: 0.916, description: "Tejabi Hallmark 91.6%" },
      { metal: "Gold", purity: "18K", fineness: 0.750, description: "18 Karat 75.0%" },
      { metal: "Gold", purity: "14K", fineness: 0.585, description: "14 Karat 58.5%" },
      { metal: "Silver", purity: "Fine (99.9%)", fineness: 0.999, description: "Fine Silver bullion" },
      { metal: "Silver", purity: "92.5% Chandi", fineness: 0.925, description: "Sterling Silver" },
      { metal: "Platinum", purity: "Pt 950", fineness: 0.950, description: "Platinum 950" }
    ],
    units: [
      { name: "Gram", symbol: "g", gramsRatio: 1.0 },
      { name: "10 Gram", symbol: "10g", gramsRatio: 10.0 },
      { name: "Tola", symbol: "Tola", gramsRatio: 11.664 }
    ],
    paymentMethods: [
      "Cash",
      "Bank Transfer",
      "QR",
      "Cheque",
      "Card",
      "Digital Wallet",
      "Other"
    ],
    defaultMakingChargeRate: 1000, // per gram or flat
    defaultWastagePercent: 7.0,
    allowNegativeStock: false,
    autoAuditRateChanges: true
  },

  loginHistory: []
};

